language: python
sudo: false
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
#   Blocked on release of fix for: https://bitbucket.org/pypy/pypy/issue/1946
#   - TOXENV=pypy3
install:
    - travis_retry pip install tox
script:
    - tox
notifications:
    email: false
